title: Portus
description: Claim control of your Docker images
exclude: [LICENSE, README.md, yarn.lock, Gemfile, Gemfile.lock, config, node_modules, Rakefile, vendor]

timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge

collections:
  docs:
    output: true
    permalink: /docs/:path.html
  setups:
    output: true
    permalink: /docs/setups/:path.html
  features:
    output: true
    permalink: /features/:path.html
  faq:
    output: false

# By default, assume the post layout.
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

sass:
  style: compressed
  sass_dir: stylesheets/partials

##
# Plugins

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num"
